topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : keyboard
  topic   : keyboard/cmd_vel
  timeout : 0.5
  priority: 8
- name    : safety
  topic   : safety_controller/cmd_vel
  timeout : 0.5
  priority: 200
 
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
